title:              RoboQuick
email:              davis.krasts@gmail.com
description:        We are a team from Latvia
author:             RoboQuick
baseurl:            "/"
url:                "https://FoxRio.github.io"

# Social Profiles

github_username:    FoxRio
facebook_username:  RoboQuick
instagram_username: roboquickvpvg 


# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
